import { ApiResponse, ApplicationType, PostApplicationType } from "../types";
import { api } from "./api.ts";

export const applicationsApi = api.injectEndpoints({
    endpoints: (build) => ({
        getAllApplications: build.query<ApplicationType[], void>({
            query: () => "jobapplications",
            providesTags: ["JobApplications"]
        }),
        /**
         * postOneApplication
         * ------------------------
         * Calls the API POST request *${apiBaseUrl}/jobapplication*
         * @param jobApplication data sent to the server to save the new application
         * @returns response is the created object if
         * there aren't any errors, or returns the errors generated by the server
         */
        postOneApplication: build.mutation<
            ApplicationType,
            PostApplicationType
        >({
            query(jobApplication) {
                return {
                    url: `jobapplication`,
                    method: "POST",
                    body: { jobApplication }
                };
            },
            invalidatesTags: ["PostedJobApplication"]
        }),
        /**
         * deleteOneApplication
         * ------------------------
         * Calls the API DELETE request *${apiBaseUrl}/jobapplication?id=[job_app_ID]*
         * @returns an information message or an error message
         */
        deleteOneApplication: build.mutation<ApiResponse, string>({
            query(id) {
                return {
                    url: `jobapplication?id=${id}`,
                    method: "DELETE"
                };
            },
            invalidatesTags: ["DeletedJobApplication"]
        })
    })
});

export const { useGetAllApplicationsQuery } = applicationsApi;
